spring:
  datasource:
    url: jdbc:postgresql://35.192.116.86:5432/postgres
    username: khermstad
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

